spring:
  datasource:
    url: jdbc:mysql://localhost:3306/task_db?createDatabaseIfNotExist=true
    username: root
    password: 112224448
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
  application:
    name: task
