spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rentcloud_vehicle?createDatabaseIfNotExist=true
    username: root
    password: 112224448
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
  application:
    name: vehicle
server:
  port: 0
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}-${random.int}
    hostname: localhost